steps:
  - name: 'gcr.io/cloud-builders/mvn'
    id: DEPLOY
    args: ['-Ddocker.image.prefix=gcr.io/ceres-dev-222017', 'package', 'jib:dockerBuild']

images:
  - 'gcr.io/ceres-dev-222017/metrics-rollup-service'
  - 'gcr.io/ceres-dev-222017/metrics-rollup-service:$BRANCH_NAME'
  - 'gcr.io/ceres-dev-222017/metrics-rollup-service:$SHORT_SHA'
