
---
spring:
  profiles: development

kafka:
  servers: ${KAFKA_SERVERS_TEST}

  ssl:
    truststore-location: ${TRUSTSTORE_LOCATION}
    truststore-password: ${TRUSTSTORE_PASSWORD}
    keystore-location: ${KEYSTORE_LOCATION}
    keystore-password: ${KEYSTORE_PASSWORD}
    key-password: ${KEY_PASSWORD}
  properties:
    security-protocol: SSL

  topics:
    in: unified.metrics.json
    out-level-1: unified.metrics.json.5m
    out-level-2: unified.metrics.json.20m
    out-level-3: unified.metrics.json.60m
    out-level-4: unified.metrics.json.240m
    out-level-5: unified.metrics.json.1440M

  consumer:
    auto-offset-reset-config: "earliest"

  streams:
    application-id-config: "rollup" # ${APPLICATION_ID_CONFIG}
    state-dir-config: "/tmp/kafka-streams" # ${STATE_DIR_CONFIG}

    aggregation:
      window-size-in-minutes-level-1: 5     # tumbling window size for aggregation
      window-size-in-minutes-level-2: 20
      window-size-in-minutes-level-3: 60
      window-size-in-minutes-level-4: 240
      window-size-in-minutes-level-5: 1440
      late-arrival-in-minutes: 4            # for late arrival of records

logging:
  level:
    com.rackspacecloud: debug
    org.springframework:
      kafka: debug
---
spring:
  profiles: production

kafka:
  servers: ${KAFKA_SERVERS}

  ssl:
    truststore-location: ${TRUSTSTORE_LOCATION}
    truststore-password: ${TRUSTSTORE_PASSWORD}
    keystore-location: ${KEYSTORE_LOCATION}
    keystore-password: ${KEYSTORE_PASSWORD}
    key-password: ${KEY_PASSWORD}
  properties:
    security-protocol: SSL

  topics:
    in: unified.metrics.json
    out-level-1: unified.metrics.json.5m
    out-level-2: unified.metrics.json.20m
    out-level-3: unified.metrics.json.60m
    out-level-4: unified.metrics.json.240m
    out-level-5: unified.metrics.json.1440M

  consumer:
    auto-offset-reset-config: "earliest"

  streams:
    application-id-config: "rollup-1m" # ${APPLICATION_ID_CONFIG}
    state-dir-config: "/tmp/kafka-streams" # ${STATE_DIR_CONFIG}

    aggregation:
      window-size-in-minutes-level-1: 5     # tumbling window size for aggregation
      window-size-in-minutes-level-2: 20
      window-size-in-minutes-level-3: 60
      window-size-in-minutes-level-4: 240
      window-size-in-minutes-level-5: 1440
      late-arrival-in-minutes: 4            # for late arrival of records
