
---
spring:
  profiles: development

kafka:
  servers: ${KAFKA_SERVERS_TEST}

  ssl:
    truststore-location: ${TRUSTSTORE_LOCATION}
    truststore-password: ${TRUSTSTORE_PASSWORD}
    keystore-location: ${KEYSTORE_LOCATION}
    keystore-password: ${KEYSTORE_PASSWORD}
    key-password: ${KEY_PASSWORD}
  properties:
    security-protocol: SSL

  topics:
    in: unified.metrics.json
    out: unified.metrics.json.5m

  consumer:
    auto-offset-reset-config: "earliest"

  streams:
    application-id-config: "rollup-1m" # ${APPLICATION_ID_CONFIG}
    state-dir-config: "/tmp/kafka-streams" # ${STATE_DIR_CONFIG}

    aggregation:
      window-size-in-minutes: 1   # tumbling window size for aggregation
      window-retention-period-in-minutes: 2 # for late arrival of records

logging:
  level:
    com.rackspacecloud: debug
    org.springframework:
      kafka: debug
---
spring:
  profiles: production

kafka:
  servers: ${KAFKA_SERVERS_TEST}

  ssl:
    truststore-location: ${TRUSTSTORE_LOCATION}
    truststore-password: ${TRUSTSTORE_PASSWORD}
    keystore-location: ${KEYSTORE_LOCATION}
    keystore-password: ${KEYSTORE_PASSWORD}
    key-password: ${KEY_PASSWORD}
  properties:
    security-protocol: SSL

  topics:
    in: unified.metrics.json
    out: unified.metrics.json.5m

  consumer:
    auto-offset-reset-config: "earliest"

  streams:
    application-id-config: "rollup-1m" # ${APPLICATION_ID_CONFIG}
    state-dir-config: "/tmp/kafka-streams" # ${STATE_DIR_CONFIG}

    aggregation:
      window-size-in-minutes: 2   # tumbling window size for aggregation
      window-retention-period-in-minutes: 10 # for late arrival of records
